name: WakaTime Readme

on:
  schedule:
    - cron: "0 0 * * *" # chạy mỗi ngày vào 00:00 UTC
  workflow_dispatch:      # cho phép chạy tay

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
